
auth {
    fingerprint:enabled = 1
    fingerprint:ready_message = (Scan fingerprint to unlock)
    fingerprint:present_message = Scanning fingerprint
    fingerprint:retry_delay = 250
}

general {
    grace = 1
    ignore_empty_input = true
}

background {
    monitor =
    path = ~/.config/hypr/tron2.png
    blur_passes = 3
    blur_size = 3
}

animation {
    enabled = yes
}

input-field {
    monitor =
    size = 280, 58
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = -1
    outer_color = rgba(fab489ff)
    inner_color = rgba(1e1e2ecc)
    font_color = rgba(cdd6f4ff)
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <i>Password...</i>
    hide_input = false
    rounding = 28
    check_color = rgba(a6e3a1ff)
    fail_color = rgba(f38ba8ff)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false
    position = 0, 200
    halign = center
    valign = bottom
    shadow_passes = 3
    shadow_size = 8
    shadow_color = rgba(00000099)
    shadow_boost = 1.2
}

# Date
label {
    monitor =
    text = cmd[update:18000000] date +'<b>%A, %-d %B %Y</b>'
    color = rgba(cdd6f4ff)
    font_size = 30
    font_family = SF Pro Display
    position = 0, -100
    halign = center
    valign = top
}

# Week
label {
    monitor =
    text = cmd[update:18000000] date +'<b>Week %U</b>'
    color = rgba(fab489ff)
    font_size = 15
    font_family = FiraCode Nerd Font
    position = 0, -55
    halign = center
    valign = top
    shadow_passes = 3
    shadow_size = 8
}

# Time
label {
    monitor =
    text = cmd[update:1000] date +'<b><big>%H:%M:%S</big></b>'
    color = rgba(f4d6cdff)
    font_size = 92
    font_family = SF Pro Display
    position = 0, -125
    halign = center
    valign = top
}

# User
label {
    monitor =
    text =   $USER
    color = rgba(cdd6f4ff)
    font_size = 18
    font_family = Lexend
    position = 0, 100
    halign = center
    valign = bottom
    shadow_passes = 3
    shadow_size = 8
}

# Uptime
label {
    monitor =
    text = cmd[update:60000] uptime -p
    color = rgba(cdd6f4ff)
    font_size = 20
    font_family = FiraCode Nerd Font
    position = -50, 20
    halign = right
    valign = bottom
    shadow_passes = 3
    shadow_size = 8
}
